deepseek:
  base_url: "https://api.deepseek.com/v1"
  api_key: "abc_sk-2f77d8d8f2bb4941a5776d46e3132606"
  completion_model: "deepseek-chat"

qdrant:
  url: "http://47.103.39.33:6333"
  api_key: ""  # 如果没有设置 API 密钥,保持为空字符串
  collection_name: "pillow"


database:
  username: "pillow"
  password: "1234QWERasdf!@#$"
  host: "81.68.235.167"
  port: "5432"
  dbname: "pillow_customer_prod"

speech_api:
  appid: "6876644863"
  access_token: "abc_SmjmNcd4sPVl5FqLi7U6Gvs8WtF0yMlF"
  secret_key: "abc_qbQn3ScXJDr4mxUJ22yCgoUqhmW9OmoU"
  cluster: "volcano_mega"
  voice_type: "S_LDfNJ5E11"
  host: "openspeech.bytedance.com"

oss_key:
  access_key_id: "abc_LTAI5tQLC1ShqDBV6VKuLhrZ"
  access_key_secret: "abc_yd4IxfCS977axJtU1D7Q7kOKiC3TTV"
  endpoint: "oss-cn-shanghai.aliyuncs.com"
  bucket_name: "pillow-chat"


logger:
  "path": "logs/access.log",
  "level": "info",
  "rotation": "20 days",
  "retention": "1 months",
  "format": "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  