deepseek:
  base_url: "https://api.deepseek.com/v1"
  api_key: "sk-2f77d8d8f2bb4941a5776d46e3132606"
  completion_model: "deepseek-chat"

speech_api:
  provider: "your-speech-api-provider"
  api_key: "your-speech-api-key"
  region: "your-speech-api-region"

qdrant:
  url: "http://47.103.39.33:6333"
  api_key: ""  # 如果没有设置 API 密钥,保持为空字符串
  collection_name: "pillow"


database:
  username: "pillow"
  password: "1234QWERasdf!@#$"
  host: "81.68.235.167"
  port: "5432"
  dbname: "pillow_customer_prod"

speech_api:
  appid: "6876644863"
  access_token: "SmjmNcd4sPVl5FqLi7U6Gvs8WtF0yMlF"
  secret_key: qbQn3ScXJDr4mxUJ22yCgoUqhmW9OmoU
  cluster: "volcano_mega"
  voice_type: "S_LDfNJ5E11"
  host: "openspeech.bytedance.com"