deepseek:
  base_url: "https://api.deepseek.com/v1"
  api_key: "YOUR_DEEPSEEK_API_KEY"
  completion_model: "deepseek-chat"

qdrant:
  url: "http://your.qdrant.url:6333"
  api_key: ""  # 如果没有设置 API 密钥,保持为空字符串
  collection_name: "pillow"


database:
  username: "your_db_username"
  password: "your_db_password"
  host: "your.db.host"
  port: "5432"
  dbname: "your_db_name"

speech_api:
  appid: "YOUR_SPEECH_API_APPID"
  access_token: "YOUR_SPEECH_API_ACCESS_TOKEN"
  secret_key: "YOUR_SPEECH_API_SECRET_KEY"
  cluster: "volcano_mega"
  voice_type: "S_LDfNJ5E11"
  host: "openspeech.bytedance.com"

oss_key:
  access_key_id: "YOUR_OSS_ACCESS_KEY_ID"
  access_key_secret: "YOUR_OSS_ACCESS_KEY_SECRET"
  endpoint: "oss-cn-shanghai.aliyuncs.com"
  bucket_name: "your-bucket-name"


logger:
  "path": "logs/access.log",
  "level": "info",
  "rotation": "20 days",
  "retention": "1 months",
  "format": "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  
