llm:
  api_base: "https://u231521-ad4b-8cc0be84.westb.seetacloud.com:8443/chat"
  completion_model: "qwen"
  max_retries: 2
  retry_delay: 1

qdrant:
  url: "http://47.103.39.33:6333"
  api_key: ""  # 如果没有设置 API 密钥,保持为空字符串
  collection_name: "pillow"

database:
  username: "pillow"
  password: "1234QWERasdf!@#$"
  host: "81.68.235.167"
  port: "5432"
  dbname: "pillow_customer_prod"

speech_api:
  appid: "6876644863"
  access_token: "SmjmNcd4sPVl5FqLi7U6Gvs8WtF0yMlF"
  secret_key: "qbQn3ScXJDr4mxUJ22yCgoUqhmW9OmoU"
  cluster: "volcano_mega"
  voice_type: "S_LDfNJ5E11"
  host: "openspeech.bytedance.com"




logger:
  path: "logs/access.log"
  level: "info"
  rotation: "20 days"
  retention: "1 months"
  format: "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  
# qdrant:
#   url: "http://your.qdrant.url:6333"
#   api_key: ""  # 如果没有设置 API 密钥,保持为空字符串
#   collection_name: "pillow"


# database:
#   username: "your_db_username"
#   password: "your_db_password"
#   host: "your.db.host"
#   port: "5432"
#   dbname: "your_db_name"

# speech_api:
#   appid: "YOUR_SPEECH_API_APPID"
#   access_token: "YOUR_SPEECH_API_ACCESS_TOKEN"
#   secret_key: "YOUR_SPEECH_API_SECRET_KEY"
#   cluster: "volcano_mega"
#   voice_type: "S_LDfNJ5E11"
#   host: "openspeech.bytedance.com"

# oss_key:
#   access_key_id: "YOUR_OSS_ACCESS_KEY_ID"
#   access_key_secret: "YOUR_OSS_ACCESS_KEY_SECRET"
#   endpoint: "oss-cn-shanghai.aliyuncs.com"
#   bucket_name: "your-bucket-name"


# logger:
#   "path": "logs/access.log"
#   "level": "info"
#   "rotation": "20 days"
#   "retention": "1 months"
#   "format": "<level>{level: <8}</level> <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> request id: {extra[request_id]} - <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  
